### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by VictorKong94** [berkeley-stat159/project-delta#70]
@liuanna I can see that you uploaded test data to dropbox. Can you give me summary of where it's from? I was actually thinking of making a set of test_data from scratch instead.

**Comment by liuanna** [comment]
The all test data come from subject001, BOLD and hehav folders, task001_run001. From now on, we only need behavdata.txt and bold.nii.gz for all run and all subjects. The rest of the files in the folder ds005   can be deleted.

**Comment by VictorKong94** [comment]
I don't think it's a good idea to use the actual data to test our functions. I made test data from the most recent commits. Can you take a look at them some time and let me know if it's okay to use instead?

**Comment by liuanna** [comment]
Hi Victor, 
You did a good job and I think you are right that we should not use actual data for testing functions. So, we'd better use the test data you made and this will also avoid problems when running coverage. Would you mind going over all test files and making some modifications? Thanks. However, please do not change the Makefile now, since I also use test_data in Makefile for scripts. I will make modifications on scripts to make them get data from data folder instead of Makefile. Thanks for pointing them out.

**Comment by VictorKong94** [comment]
Thanks for replying so quickly. Working on it now. Good luck on your project. (y)
