### ISSUE TITLE
Week 11(Nov 2-8) Project Plan and Goals

### ISSUE THREAD

**Issue by liuanna** [berkeley-stat159/project-delta#8]
* Review the paper "The Statistical Analysis of fMRI Data"
* Revisit the proposal and determine the goal of the project
* Select/filter data
* Office Hour with Jarrod
* Group meeting this week TBD

Feel free to add more and give suggestions. Thanks!

**Comment by VictorKong94** [comment]
I want to regress response time and probability of acceptance on variables that relate to the nature of the individuals (e.g., perhaps older subjects were quicker to respond do to having had to make more decisions).

**Comment by VictorKong94** [comment]
Anyone going to Jarrod's officer hours: "Is there a way to find out what requirements they had for recruiting subjects? For exams ample, were they non-smokers, non-drinkers, educational status, etc.?

**Comment by liuanna** [comment]
@VictorKong94 I asked Jarrod. Since the background information about subjects is not provided, we may look for new data from other resources if we really want to investigate the relationship between these features and neural response in decision-making, that is we need to get rid of our current fMRI data. Or we may try to directly contact the authors of the paper, but I think it is unlikely that they will provide these info.

**Comment by yfxia** [comment]
I went to Jarrod's office hour. We may pay special attention on the supplementary material provided at the end of our article: http://www.sciencemag.org/content/suppl/2007/01/22/315.5811.515.DC1/Tom.SOM.pdf
It wells details the how they produced the scientific graphs we see in the article. The idea is that we can possibly find something that attracts us and reproduce/verify what they mean by that. For example, I may choose to verify this "This latter variable was included because of behavioral evidence suggesting greater difficulty making a decision for trials in which participants had the weakest preference" by performing logistic regression and have some picture and hypothesis testing to just see how it turns out. Since it is a long article, we may not get to the end of it but at least all of us could find some specific point and elaborate on it.
