### ISSUE TITLE
Changes to make_class.py

### ISSUE THREAD

**Issue by VictorKong94** [berkeley-stat159/project-delta#82]
Hey, you guys realize you can't mix the affine from the filtered data with the BOLD data from the raw data, right? The raw data has its own affines, which are not the same as that for the filtered data. You either choose to use the raw data exclusively or the filtered data exclusively.

**Comment by VictorKong94** [comment]
I would also appreciate if you would run it by me before changing my functions since you wanted the same from me.

**Comment by VictorKong94** [comment]
Also looking through the merged commits now: Someone explain to me the point of making the .design_matrix() output a tuple? It seems useless to me because it can just be taken from .behav[:, 4].

**Comment by liuanna** [comment]
Yes, you are right. I think we should only use the raw data instead of filtered data since it may cause further complexity. So please remove the lines that you feel not appropriate. Sorry about that. For your second concern, I separated behave[:, 4] which is response 0 or 1 from design matrix because we should not include Y in the design matrix X.

**Comment by VictorKong94** [comment]
I think we should ask @yfxia @karenceli @j170382276 first before deciding which data set to use. The level of complexity should be the same regardless of whether we use the raw or the filtered data; the concern is that we need to pick *one*.

I agree with your point about not using the response as a regressor. I will remove these columns now. However, my question was concerning why the .design_matrix() method returns a tuple.

**Comment by yfxia** [comment]
I think we can stick to the first one for now because I planned to test my smoothing function to initially filter some data and compare the results. I'm not sure what the provided filtered data has filtered out but I just want to see how the smoothing helps. 

I'm working on run_logistic_model script right now, in that file, I will need both design matrix and response category (which are 0 and 1 in this case) outputs separately from .design_matrix(). They will be the inputs for logistic model in sklearn package. 

Does it make sense?

**Comment by VictorKong94** [comment]
I understand your concern with inputs for the sklearn package, but it's just as easy to pull the responses using .behav[:, 4]. Making the output of .design_matrix() into a tuple with something unrelated doesn't help our performance at all but is at the same time detrimental to our code's clarity.

**Comment by yfxia** [comment]
I see what you mean and I agree with it. Could you make changes on make_class.py and I will continue working on logistic model? Thanks a lot for clarification!

**Comment by yfxia** [comment]
@VictorKong94, I ran into an error when I was using the .design_matrix() function in make_class.py. 

In Line 79, design_matrix[:, 1:num_regressors] = self.behav[:, regressors], if I set euclidean_distance to False, then it will become  design_matrix[:, 1:2] = self.behav[:, regressors]. The LHS has one column, whereas the RHS has two columns.

**Comment by VictorKong94** [comment]
I haven't made a pull request since make_class.py was changed earlier. I'll do that now and you tell me if you still get the same error.

**Comment by VictorKong94** [comment]
I've run into a problem now too. The class is no longer passing my tests. Give me a bit please.

**Comment by VictorKong94** [comment]
Try it now.
