### ISSUE TITLE
Update 11/30/2015

### ISSUE THREAD

**Issue by VictorKong94** [berkeley-stat159/project-delta#90]
- [x] The `utils/` and `models/` folders have been added to Coveralls and tests now have their own separate folder so coverage is now more accurately calculated (before, only our `data/` folder was being tracked).

- [x] All necessary functionality with the exception of graphing functions have been moved from `stimuli.py`, `smoothing.py`, and `utils_functions.py` to the new `run` class, which is complete with tests. Please make the transition soon so we can get rid of these files.

- [x] Euclidean distance has been added to .behav as well instead of only `.design_matrix()`. Scripts that use `.behav` but not `.design_matrix()` now have the extra option of using euclidean distance as an input.

- [x] Single-variable correlation coefficient estimation has been added to the `run` class as the method `.correlation()`.

- [ ] Task: Please list functions in order of priority to add to `run` class and/or write tests for. Please also specify which should be done for each function (e.g., Write test for ___ AND add to `run` class).

- [x] Question: Do we need `pearson.py`?

- [x] Question: In what situation would we use `neural_highres()` instead of `events2neural()`?

**Comment by liuanna** [comment]
Regarding to the last two questions, first, we have not used the pearson.py so far, but we can keep it since I think it was already there when the repo was built.  ```neural_highres()``` handles more complicated conditions while ```events2neural()``` is for simpler cases. In our case,  ```neural_highres()``` is more suitable. 

One more thing, would you mind adding four conditions files (cond001, cond002, cond003, cond004 from ds005) to the run class as attributes, since I need to rewrite run_conv_script.py using these four condition files instead of generating our own 4 conditions from behavdata? I will upload the new run_conv_script.py tonight. I think the time_course method in run class need to be adjusted according to the new run_conv_script.py. Thanks!

**Comment by VictorKong94** [comment]
I've added `cond002.txt`, `cond003.txt`, `cond004.txt` files, but I didn't add `cond001.txt` because there's only one task for this study.

**Comment by VictorKong94** [comment]
Last set of midterms and first finals; will be MIA until Thursday night.

**Comment by yfxia** [comment]
@VictorKong94 If I decide to use filtered data, but I notice that filtered data do not have behavedata.txt but only neural data, how does make_class deal with this situation? 

Also, on my computer by default, filtered data also has the same name as 'ds005' , did you rename it on your computer?
